on:
  push:
    branches:
      - master
  path:
    - develop
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: |
          echo "Hello, World!"
